dataset_type: co3d
model: plenoxel_torch
batching: all_images

i_print: 100
i_validation: 25600

N_rand: 5000
max_steps: 51200
reso: "[[128, 128, 128], [256, 256, 256]]"
background_nlayers: 64
background_reso: 1024
upsamp_every: 25600
lr_sigma: 3.0e+1
lr_sh: 1.0e-2
lr_fg_begin_step: 1000
lr_sigma_delay_steps: 0
weight_thresh: 0.5
thresh_type: "sigma"
lambda_tv": 5.0e-5
lambda_tv_sh": 5.0e-3
lambda_tv_background_sigma": 1.0e-3
lambda_tv_background_color: 1.0e-3
lambda_beta: 1.0e-5
lambda_sparsity: 1.0e-11
background_brightness: 0.5
tv_early_only: 0
tv_decay: 0.5

postfix: "_small"

store_result_json: True
ndc: false
