dataset_type: blender
batching: single_image
factor: 0

num_coarse_samples: 64
num_fine_samples: 128

N_rand: 4096
perturb: 1.0
white_bkgd: true

lr_init: 5.0e-4
lr_final: 5.0e-6
lr_delay_steps: 5000
lr_delay_mult: 0.2
max_steps: 200000

i_print: 100
i_weights: 50000
i_validation: 50000
use_pixel_centers: true

netwidth: 256
netwidth_fine: 256

no_ndc: true
